name: Static Analysis Test

on: [push]

permissions:
  contents: read

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - bl1_process.h
          - bl1_process.c
          
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck
      - name: Run cppcheck on ${{ matrix.file }}
        run: cppcheck --enable=all --inconclusive -I test-cases test-cases/${{ matrix.file }}
